server:
  port: 8762
 
spring:
  application:    name: zuul-gateway 
    
zuul:
  routes:    mobile-service:
      path: /mobile-service/**
      serviceId : MOBILE-SERVICE
      sensitiveHeaders: Cookie,Set-Cookie
    country-service:
      path: /country-service/**
      serviceId : COUNTRY-SERVICE
      sensitiveHeaders: Cookie,Set-Cookie
    mobile-accessory:
      path: /mobile-accessory/**
      serviceId : MOBILE-ACCESSORY
      sensitiveHeaders: Cookie,Set-Cookie
  host:
    connect-timeout-millis: 10000 # starting the connection 
    socket-timeout-millis: 10000  # monitor the continuous incoming data flow
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    
       
 
